'use strict';
var Server = require('./frontend/server.js');
var express = require('express');
var path = require('path');
var app = Server.app();
var _ = require('underscore');
module.exports = app;
app.use('/', express.static(path.join(__dirname, "../Public")));
const port = process.env.PORT ? process.env.PORT : (process.env.NODE_ENV === 'test' ? 4000 : 3000);
console.log('running on port', port);
app.listen(port);
